/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rdlshewto5dulapoekv7zpsyai.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jn4ng3sfzzd6vhsbarntti7bzu",
    "aws_cognito_identity_pool_id": "us-east-1:4592b247-d6ea-48d1-8f7f-23051d6b8f9f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_61FyutHWp",
    "aws_user_pools_web_client_id": "3bl47e74emgqb2uhub38fbnr3f",
    "oauth": {}
};


export default awsmobile;
